var damageDescriptions = [
    "Blade Collar Misalignment",
    "Blade Weight Balancing",
    "Broken Down Conductor at Root End",
    "Carbon Cap/Pultrusion Damage",
    "Carbon Spar Damage 44m Blade",
    "Carbon Spar Damage 49m Blade",
    "Carbon Spar Damage 55m Blade",
    "Chordwise Crack at R13 Trailing Edge",
    "Coat Damage",
    "Cooler Top Crack",
    "Copper Cap Installation",
    "Copper Cap Retrofit",
    "Copper Cap and Copper Strips Installation",
    "Copper Strip Damage",
    "Copper Strips Installation",
    "Crack around Lightning Bolt (Receptor)",
    "Crack around SPL Bolt",
    "Crack in SMT implant",
    "Crack near Tip 49m Blades",
    "Damper Tank",
    "Damper Tank Leak",
    "Description",
    "Down Conductor - Tip Implant Damage V90 - V117",
    "Down Conductor - Tip Receptor Damage V47 - V66",
    "Edgewise Vibration Damage",
    "Edgewise Vibration Damage 44m Blade",
    "Edgewise Vibration Damage 49m Blade",
    "Flat Trailing Edge Crack",
    "Gurney Flap Damage",
    "Hole in Leading Edge close to Tip due to T-Sensor Wire",
    "Ice Detection Sensor - Bosch rexroth (IGUS)",
    "LCTU Damage",
    "Leading Edge Damage",
    "Leading Edge Erosion",
    "Leading Edge Root Crack",
    "Leading Edge Spanwise Crack",
    "Leading Edge Tape Damage",
    "Lengthwise Cracks",
    "Lightning Band",
    "Lightning Band Damage",
    "Lightning Bolt (Receptor) Damage",
    "Lightning Detector Damage",
    "Lightning Hit on Copper Cap",
    "Lightning Hit on Copper Strips",
    "Lightning Hit on Receptor",
    "Lightning Hit on SMT",
    "Lightning Receptor Screw Damage",
    "Load Sensor Damage",
    "Missing Seal between SMT & Blade Shell",
    "No damage has been found",
    "Oil in Blades",
    "Paint Erosion on Copper Cap",
    "Paint Erosion on SMT",
    "Root Crack",
    "Root Vortex Generator Damage",
    "SMT bending in TE",
    "SMT melted TE",
    "Serrated Trailing Edge (STE)",
    "Shell Damage",
    "Shell Web Bonding",
    "Spar Damage V47-V80",
    "Stall Strips Damage",
    "TC Mark misplaced",
    "TE Damage",
    "TE Damage at Tip",
    "Tip Damage",
    "Tip Shell Replacement",
    "V100 TE cracks in Root End",
    "V112-126 De-Icing System Failure",
    "V82 Root Inserts",
    "Vortex Generator Damage",
    "Web Bonding",
    "Wrinkles in TE Stringer"
];
