//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class BearingType
    {
        public BearingType()
        {
            this.BearingType1 = new HashSet<BearingType>();
            this.ComponentInspectionReportGearbox = new HashSet<ComponentInspectionReportGearbox>();
            this.ComponentInspectionReportGearbox1 = new HashSet<ComponentInspectionReportGearbox>();
            this.ComponentInspectionReportGearbox2 = new HashSet<ComponentInspectionReportGearbox>();
            this.ComponentInspectionReportGearbox3 = new HashSet<ComponentInspectionReportGearbox>();
            this.ComponentInspectionReportGearbox4 = new HashSet<ComponentInspectionReportGearbox>();
            this.ComponentInspectionReportGearbox5 = new HashSet<ComponentInspectionReportGearbox>();
        }
    
        public long BearingTypeId { get; set; }
        public string Name { get; set; }
        public long LanguageId { get; set; }
        public Nullable<long> ParentBearingTypeId { get; set; }
        public long Sort { get; set; }
        public string Brand { get; set; }
    
        public virtual ICollection<BearingType> BearingType1 { get; set; }
        public virtual BearingType BearingType2 { get; set; }
        public virtual ICollection<ComponentInspectionReportGearbox> ComponentInspectionReportGearbox { get; set; }
        public virtual ICollection<ComponentInspectionReportGearbox> ComponentInspectionReportGearbox1 { get; set; }
        public virtual ICollection<ComponentInspectionReportGearbox> ComponentInspectionReportGearbox2 { get; set; }
        public virtual ICollection<ComponentInspectionReportGearbox> ComponentInspectionReportGearbox3 { get; set; }
        public virtual ICollection<ComponentInspectionReportGearbox> ComponentInspectionReportGearbox4 { get; set; }
        public virtual ICollection<ComponentInspectionReportGearbox> ComponentInspectionReportGearbox5 { get; set; }
    }
}
