//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class BladeLength
    {
        public BladeLength()
        {
            this.BladeLength1 = new HashSet<BladeLength>();
            this.ComponentInspectionReportBlade = new HashSet<ComponentInspectionReportBlade>();
        }
    
        public long BladeLengthId { get; set; }
        public string Name { get; set; }
        public long LanguageId { get; set; }
        public Nullable<long> ParentBladeLengthId { get; set; }
        public long Sort { get; set; }
        public string Brand { get; set; }
    
        public virtual ICollection<BladeLength> BladeLength1 { get; set; }
        public virtual BladeLength BladeLength2 { get; set; }
        public virtual ICollection<ComponentInspectionReportBlade> ComponentInspectionReportBlade { get; set; }
    }
}
