//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class BladeEdge
    {
        public BladeEdge()
        {
            this.BladeEdge1 = new HashSet<BladeEdge>();
            this.ComponentInspectionReportBladeDamage = new HashSet<ComponentInspectionReportBladeDamage>();
        }
    
        public long BladeEdgeId { get; set; }
        public string Name { get; set; }
        public long LanguageId { get; set; }
        public Nullable<long> ParentBladeEdgeId { get; set; }
        public long Sort { get; set; }
        public int StartVersion { get; set; }
        public int EndVersion { get; set; }
    
        public virtual ICollection<BladeEdge> BladeEdge1 { get; set; }
        public virtual BladeEdge BladeEdge2 { get; set; }
        public virtual ICollection<ComponentInspectionReportBladeDamage> ComponentInspectionReportBladeDamage { get; set; }
    }
}
