//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIMCase
    {
        public int DCIMCaseID { get; set; }
        public int CaseNo { get; set; }
        public string Description { get; set; }
        public string Platform { get; set; }
        public string ComponentName { get; set; }
        public string ComponentClass { get; set; }
    }
}
