//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CirAttachment
    {
        public long CirAttachmentId { get; set; }
        public long CirId { get; set; }
        public string Filename { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
        public byte[] BinaryData { get; set; }
    }
}
