//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CirCommentHistory
    {
        public long CirCommentHistoryId { get; set; }
        public long CirDataId { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
        public string Initials { get; set; }
        public byte Type { get; set; }
    
        public virtual CirData CirData { get; set; }
    }
}
