//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CirFieldMappings
    {
        public long CirFieldMappingID { get; set; }
        public string ColumnName { get; set; }
        public string TableName { get; set; }
        public string ColumnDisplayName { get; set; }
        public Nullable<int> FieldLookupId { get; set; }
        public string Type { get; set; }
        public string GuiID { get; set; }
        public Nullable<int> isDefault { get; set; }
    }
}
