//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CirMailArchive
    {
        public long CirMailArchiveId { get; set; }
        public long CirDataId { get; set; }
        public string Mail { get; set; }
        public short Type { get; set; }
        public System.DateTime Date { get; set; }
        public bool Deleted { get; set; }
    }
}
