//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CirSystemLog
    {
        public long CirSystemLogId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public short Type { get; set; }
        public string Message { get; set; }
        public string Details { get; set; }
    }
}
