//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CirView
    {
        public int CirViewId { get; set; }
        public string ViewData { get; set; }
        public short Type { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> InspectionApplicable { get; set; }
        public string CirViewData { get; set; }
        public Nullable<bool> GBXInspectionApplicable { get; set; }
        public Nullable<bool> GeneralInspectionApplicable { get; set; }
    }
}
