//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentInspectionReportGearbox
    {
        public long ComponentInspectionReportGearboxId { get; set; }
        public long ComponentInspectionReportId { get; set; }
        public string VestasUniqueIdentifier { get; set; }
        public long GearboxTypeId { get; set; }
        public long GearboxRevisionId { get; set; }
        public long GearboxManufacturerId { get; set; }
        public string OtherGearboxType { get; set; }
        public string GearboxSerialNumber { get; set; }
        public string GearboxOtherManufacturer { get; set; }
        public Nullable<System.DateTime> GearboxLastOilChangeDate { get; set; }
        public long GearboxOilTypeId { get; set; }
        public long GearboxMechanicalOilPumpId { get; set; }
        public long GearboxOilLevelId { get; set; }
        public Nullable<long> GearboxRunHours { get; set; }
        public decimal GearboxOilTemperature { get; set; }
        public Nullable<long> GearboxProduction { get; set; }
        public Nullable<long> GearboxGeneratorManufacturerId { get; set; }
        public Nullable<long> GearboxGeneratorManufacturerId2 { get; set; }
        public Nullable<long> GearboxElectricalPumpId { get; set; }
        public Nullable<long> GearboxShrinkElementId { get; set; }
        public string GearboxShrinkElementSerialNumber { get; set; }
        public Nullable<long> GearboxCouplingId { get; set; }
        public Nullable<long> GearboxFilterBlockTypeId { get; set; }
        public Nullable<long> GearboxInLineFilterId { get; set; }
        public Nullable<long> GearboxOffLineFilterId { get; set; }
        public string GearboxSoftwareRelease { get; set; }
        public Nullable<long> GearboxShaftsExactLocation1ShaftTypeId { get; set; }
        public Nullable<long> GearboxShaftsExactLocation2ShaftTypeId { get; set; }
        public Nullable<long> GearboxShaftsExactLocation3ShaftTypeId { get; set; }
        public Nullable<long> GearboxShaftsExactLocation4ShaftTypeId { get; set; }
        public Nullable<long> GearboxShaftsTypeofDamage1ShaftErrorId { get; set; }
        public Nullable<long> GearboxShaftsTypeofDamage2ShaftErrorId { get; set; }
        public Nullable<long> GearboxShaftsTypeofDamage3ShaftErrorId { get; set; }
        public Nullable<long> GearboxShaftsTypeofDamage4ShaftErrorId { get; set; }
        public Nullable<long> GearboxExactLocation1GearTypeId { get; set; }
        public Nullable<long> GearboxExactLocation2GearTypeId { get; set; }
        public Nullable<long> GearboxExactLocation3GearTypeId { get; set; }
        public Nullable<long> GearboxExactLocation4GearTypeId { get; set; }
        public Nullable<long> GearboxExactLocation5GearTypeId { get; set; }
        public Nullable<long> GearboxTypeofDamage1GearErrorId { get; set; }
        public Nullable<long> GearboxTypeofDamage2GearErrorId { get; set; }
        public Nullable<long> GearboxTypeofDamage3GearErrorId { get; set; }
        public Nullable<long> GearboxTypeofDamage4GearErrorId { get; set; }
        public Nullable<long> GearboxTypeofDamage5GearErrorId { get; set; }
        public Nullable<long> GearboxBearingsLocation1BearingTypeId { get; set; }
        public Nullable<long> GearboxBearingsLocation2BearingTypeId { get; set; }
        public Nullable<long> GearboxBearingsLocation3BearingTypeId { get; set; }
        public Nullable<long> GearboxBearingsLocation4BearingTypeId { get; set; }
        public Nullable<long> GearboxBearingsLocation5BearingTypeId { get; set; }
        public Nullable<long> GearboxBearingsPosition1BearingPosId { get; set; }
        public Nullable<long> GearboxBearingsPosition2BearingPosId { get; set; }
        public Nullable<long> GearboxBearingsPosition3BearingPosId { get; set; }
        public Nullable<long> GearboxBearingsPosition4BearingPosId { get; set; }
        public Nullable<long> GearboxBearingsPosition5BearingPosId { get; set; }
        public Nullable<long> GearboxBearingsDamage1BearingErrorId { get; set; }
        public Nullable<long> GearboxBearingsDamage2BearingErrorId { get; set; }
        public Nullable<long> GearboxBearingsDamage3BearingErrorId { get; set; }
        public Nullable<long> GearboxBearingsDamage4BearingErrorId { get; set; }
        public Nullable<long> GearboxBearingsDamage5BearingErrorId { get; set; }
        public Nullable<long> GearboxPlanetStage1HousingErrorId { get; set; }
        public Nullable<long> GearboxPlanetStage2HousingErrorId { get; set; }
        public Nullable<long> GearboxHelicalStageHousingErrorId { get; set; }
        public Nullable<long> GearboxFrontPlateHousingErrorId { get; set; }
        public Nullable<long> GearboxAuxStageHousingErrorId { get; set; }
        public Nullable<long> GearboxHSStageHousingErrorId { get; set; }
        public bool GearboxLooseBolts { get; set; }
        public bool GearboxBrokenBolts { get; set; }
        public bool GearboxDefectDamperElements { get; set; }
        public bool GearboxTooMuchClearance { get; set; }
        public bool GearboxCrackedTorqueArm { get; set; }
        public bool GearboxNeedsToBeAligned { get; set; }
        public bool GearboxPT100Bearing1 { get; set; }
        public bool GearboxPT100Bearing2 { get; set; }
        public bool GearboxPT100Bearing3 { get; set; }
        public bool GearboxOilLevelSensor { get; set; }
        public bool GearboxOilPressure { get; set; }
        public bool GearboxPT100OilSump { get; set; }
        public bool GearboxFilterIndicator { get; set; }
        public bool GearboxImmersionHeater { get; set; }
        public bool GearboxDrainValve { get; set; }
        public bool GearboxAirBreather { get; set; }
        public bool GearboxSightGlass { get; set; }
        public bool GearboxChipDetector { get; set; }
        public long GearboxVibrationsId { get; set; }
        public long GearboxNoiseId { get; set; }
        public long GearboxDebrisOnMagnetId { get; set; }
        public long GearboxDebrisStagesMagnetPosId { get; set; }
        public long GearboxDebrisGearBoxId { get; set; }
        public Nullable<System.DateTime> GearboxMaxTempResetDate { get; set; }
        public Nullable<decimal> GearboxTempBearing1 { get; set; }
        public Nullable<decimal> GearboxTempBearing2 { get; set; }
        public Nullable<decimal> GearboxTempBearing3 { get; set; }
        public Nullable<decimal> GearboxTempOilSump { get; set; }
        public bool GearboxLSSNRend { get; set; }
        public bool GearboxIMSNRend { get; set; }
        public bool GearboxIMSRend { get; set; }
        public bool GearboxHSSNRend { get; set; }
        public bool GearboxHSSRend { get; set; }
        public bool GearboxPitchTube { get; set; }
        public bool GearboxSplitLines { get; set; }
        public bool GearboxHoseAndPiping { get; set; }
        public bool GearboxInputShaft { get; set; }
        public bool GearboxHSSPTO { get; set; }
        public Nullable<long> GearboxClaimRelevantBooleanAnswerId { get; set; }
        public Nullable<long> GearboxOverallGearboxConditionId { get; set; }
        public Nullable<long> GearboxExactLocation6GearTypeId { get; set; }
        public Nullable<long> GearboxExactLocation7GearTypeId { get; set; }
        public Nullable<long> GearboxExactLocation8GearTypeId { get; set; }
        public Nullable<long> GearboxExactLocation9GearTypeId { get; set; }
        public Nullable<long> GearboxExactLocation10GearTypeId { get; set; }
        public Nullable<long> GearboxExactLocation11GearTypeId { get; set; }
        public Nullable<long> GearboxExactLocation12GearTypeId { get; set; }
        public Nullable<long> GearboxExactLocation13GearTypeId { get; set; }
        public Nullable<long> GearboxExactLocation14GearTypeId { get; set; }
        public Nullable<long> GearboxExactLocation15GearTypeId { get; set; }
        public Nullable<long> GearboxTypeofDamage6GearErrorId { get; set; }
        public Nullable<long> GearboxTypeofDamage7GearErrorId { get; set; }
        public Nullable<long> GearboxTypeofDamage8GearErrorId { get; set; }
        public Nullable<long> GearboxTypeofDamage9GearErrorId { get; set; }
        public Nullable<long> GearboxTypeofDamage10GearErrorId { get; set; }
        public Nullable<long> GearboxTypeofDamage11GearErrorId { get; set; }
        public Nullable<long> GearboxTypeofDamage12GearErrorId { get; set; }
        public Nullable<long> GearboxTypeofDamage13GearErrorId { get; set; }
        public Nullable<long> GearboxTypeofDamage14GearErrorId { get; set; }
        public Nullable<long> GearboxTypeofDamage15GearErrorId { get; set; }
        public Nullable<long> GearboxGearDecision1DamageDecisionId { get; set; }
        public Nullable<long> GearboxGearDecision2DamageDecisionId { get; set; }
        public Nullable<long> GearboxGearDecision3DamageDecisionId { get; set; }
        public Nullable<long> GearboxGearDecision4DamageDecisionId { get; set; }
        public Nullable<long> GearboxGearDecision5DamageDecisionId { get; set; }
        public Nullable<long> GearboxGearDecision6DamageDecisionId { get; set; }
        public Nullable<long> GearboxGearDecision7DamageDecisionId { get; set; }
        public Nullable<long> GearboxGearDecision8DamageDecisionId { get; set; }
        public Nullable<long> GearboxGearDecision9DamageDecisionId { get; set; }
        public Nullable<long> GearboxGearDecision10DamageDecisionId { get; set; }
        public Nullable<long> GearboxGearDecision11DamageDecisionId { get; set; }
        public Nullable<long> GearboxGearDecision12DamageDecisionId { get; set; }
        public Nullable<long> GearboxGearDecision13DamageDecisionId { get; set; }
        public Nullable<long> GearboxGearDecision14DamageDecisionId { get; set; }
        public Nullable<long> GearboxGearDecision15DamageDecisionId { get; set; }
        public Nullable<long> GearboxBearingsLocation6BearingTypeId { get; set; }
        public Nullable<long> GearboxBearingsPosition6BearingPosId { get; set; }
        public Nullable<long> GearboxBearingsDamage6BearingErrorId { get; set; }
        public Nullable<int> GearboxBearingDecision1DamageDecisionId { get; set; }
        public Nullable<int> GearboxBearingDecision2DamageDecisionId { get; set; }
        public Nullable<int> GearboxBearingDecision3DamageDecisionId { get; set; }
        public Nullable<int> GearboxBearingDecision4DamageDecisionId { get; set; }
        public Nullable<int> GearboxBearingDecision5DamageDecisionId { get; set; }
        public Nullable<int> GearboxBearingDecision6DamageDecisionId { get; set; }
        public string GearboxDefectCategorizationScore { get; set; }
        public Nullable<int> GearboxGearDamageClass1DamageId { get; set; }
        public Nullable<int> GearboxGearDamageClass2DamageId { get; set; }
        public Nullable<int> GearboxGearDamageClass3DamageId { get; set; }
        public Nullable<int> GearboxGearDamageClass4DamageId { get; set; }
        public Nullable<int> GearboxGearDamageClass5DamageId { get; set; }
        public Nullable<int> GearboxGearDamageClass6DamageId { get; set; }
        public Nullable<int> GearboxGearDamageClass7DamageId { get; set; }
        public Nullable<int> GearboxGearDamageClass8DamageId { get; set; }
        public Nullable<int> GearboxGearDamageClass9DamageId { get; set; }
        public Nullable<int> GearboxGearDamageClass10DamageId { get; set; }
        public Nullable<int> GearboxGearDamageClass11DamageId { get; set; }
        public Nullable<int> GearboxGearDamageClass12DamageId { get; set; }
        public Nullable<int> GearboxGearDamageClass13DamageId { get; set; }
        public Nullable<int> GearboxGearDamageClass14DamageId { get; set; }
        public Nullable<int> GearboxGearDamageClass15DamageId { get; set; }
        public Nullable<long> GearboxAuxEquipmentId { get; set; }
        public Nullable<long> GearboxActionToBeTakenOnGearboxId { get; set; }
    
        public virtual BearingType BearingType { get; set; }
        public virtual BearingType BearingType1 { get; set; }
        public virtual BearingType BearingType2 { get; set; }
        public virtual BearingType BearingType3 { get; set; }
        public virtual BearingType BearingType4 { get; set; }
        public virtual BearingType BearingType5 { get; set; }
        public virtual GearboxManufacturer GearboxManufacturer { get; set; }
        public virtual GeneratorManufacturer GeneratorManufacturer { get; set; }
        public virtual GeneratorManufacturer GeneratorManufacturer1 { get; set; }
        public virtual ComponentInspectionReport ComponentInspectionReport { get; set; }
    }
}
