//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentInspectionReportSkiiPNewComponent
    {
        public long ComponentInspectionReportSkiiPNewComponentId { get; set; }
        public long ComponentInspectionReportSkiiPId { get; set; }
        public string SkiiPNewComponentVestasUniqueIdentifier { get; set; }
        public string SkiiPNewComponentVestasItemNumber { get; set; }
        public string SkiiPNewComponentSerialNumber { get; set; }
    
        public virtual ComponentInspectionReportSkiiP ComponentInspectionReportSkiiP { get; set; }
    }
}
