//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentInspectionReportBladeRepairRecord
    {
        public long ComponentInspectionReportBladeRepairRecordId { get; set; }
        public long ComponentInspectionReportBladeId { get; set; }
        public decimal BladeAmbientTemp { get; set; }
        public decimal BladeHumidity { get; set; }
        public string BladeAdditionalDocumentReference { get; set; }
        public string BladeResinType { get; set; }
        public string BladeResinTypeBatchNumbers { get; set; }
        public Nullable<System.DateTime> BladeResinTypeExpiryDate { get; set; }
        public string BladeHardenerType { get; set; }
        public string BladeHardenerTypeBatchNumbers { get; set; }
        public Nullable<System.DateTime> BladeHardenerTypeExpiryDate { get; set; }
        public string BladeGlassSupplier { get; set; }
        public string BladeGlassSupplierBatchNumbers { get; set; }
        public decimal BladeSurfaceMaxTemperature { get; set; }
        public decimal BladeSurfaceMinTemperature { get; set; }
        public long BladeResinUsed { get; set; }
        public decimal BladePostCureMaxTemperature { get; set; }
        public decimal BladePostCureMinTemperature { get; set; }
        public Nullable<System.DateTime> BladeTurnOffTime { get; set; }
        public long BladeTotalCureTime { get; set; }
    
        public virtual ComponentInspectionReportBlade ComponentInspectionReportBlade { get; set; }
    }
}
