//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentInspectionReportTransformer
    {
        public long ComponentInspectionReportTransformerId { get; set; }
        public long ComponentInspectionReportId { get; set; }
        public string VestasUniqueIdentifier { get; set; }
        public long TransformerManufacturerId { get; set; }
        public string TransformerSerialNumber { get; set; }
        public Nullable<decimal> MaxTemp { get; set; }
        public Nullable<System.DateTime> MaxTempResetDate { get; set; }
        public long ActionOnTransformerId { get; set; }
        public long HVCoilConditionId { get; set; }
        public long LVCoilConditionId { get; set; }
        public long HVCableConditionId { get; set; }
        public long LVCableConditionId { get; set; }
        public long BracketsId { get; set; }
        public long TransformerArcDetectionId { get; set; }
        public long ClimateId { get; set; }
        public long SurgeArrestorId { get; set; }
        public long ConnectionBarsId { get; set; }
        public string Comments { get; set; }
        public Nullable<long> TransformerClaimRelevantBooleanAnswerId { get; set; }
    
        public virtual TransformerManufacturer TransformerManufacturer { get; set; }
        public virtual ComponentInspectionReport ComponentInspectionReport { get; set; }
    }
}
