//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentInspectionReportGeneral
    {
        public long ComponentInspectionReportGeneralId { get; set; }
        public long ComponentInspectionReportId { get; set; }
        public Nullable<long> GeneralComponentGroupId { get; set; }
        public string GeneralComponentType { get; set; }
        public string VestasUniqueIdentifier { get; set; }
        public string GeneralComponentManufacturer { get; set; }
        public string GeneralOtherGearboxType { get; set; }
        public Nullable<long> GeneralClaimRelevantBooleanAnswerId { get; set; }
        public string GeneralOtherGearboxManufacturer { get; set; }
        public string GeneralComponentSerialNumber { get; set; }
        public Nullable<long> GeneralGeneratorManufacturerId { get; set; }
        public Nullable<long> GeneralTransformerManufacturerId { get; set; }
        public Nullable<long> GeneralGearboxManufacturerId { get; set; }
        public Nullable<long> GeneralTowerTypeId { get; set; }
        public Nullable<long> GeneralTowerHeightId { get; set; }
        public string GeneralBlade1SerialNumber { get; set; }
        public string GeneralBlade2SerialNumber { get; set; }
        public string GeneralBlade3SerialNumber { get; set; }
        public Nullable<long> GeneralControllerTypeId { get; set; }
        public string GeneralSoftwareRelease { get; set; }
        public Nullable<long> GeneralRamDumpNumber { get; set; }
        public Nullable<long> GeneralVDFTrackNumber { get; set; }
        public long GeneralPicturesIncludedBooleanAnswerId { get; set; }
        public string GeneralInitiatedBy1 { get; set; }
        public string GeneralInitiatedBy2 { get; set; }
        public string GeneralInitiatedBy3 { get; set; }
        public string GeneralInitiatedBy4 { get; set; }
        public string GeneralMeasurementsConducted1 { get; set; }
        public string GeneralMeasurementsConducted2 { get; set; }
        public string GeneralMeasurementsConducted3 { get; set; }
        public string GeneralMeasurementsConducted4 { get; set; }
        public string GeneralExecutedBy1 { get; set; }
        public string GeneralExecutedBy2 { get; set; }
        public string GeneralExecutedBy3 { get; set; }
        public string GeneralExecutedBy4 { get; set; }
        public string GeneralPositionOfFailedItem { get; set; }
    
        public virtual GearboxManufacturer GearboxManufacturer { get; set; }
        public virtual GeneratorManufacturer GeneratorManufacturer { get; set; }
        public virtual TransformerManufacturer TransformerManufacturer { get; set; }
        public virtual ComponentInspectionReport ComponentInspectionReport { get; set; }
    }
}
