//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentInspectionReportBlade
    {
        public ComponentInspectionReportBlade()
        {
            this.ComponentInspectionReportBladeDamage = new HashSet<ComponentInspectionReportBladeDamage>();
            this.ComponentInspectionReportBladeRepairRecord = new HashSet<ComponentInspectionReportBladeRepairRecord>();
        }
    
        public long ComponentInspectionReportBladeId { get; set; }
        public long ComponentInspectionReportId { get; set; }
        public string VestasUniqueIdentifier { get; set; }
        public long BladeLengthId { get; set; }
        public long BladeColorId { get; set; }
        public string BladeSerialNumber { get; set; }
        public long BladePicturesIncludedBooleanAnswerId { get; set; }
        public string BladeOtherSerialNumber1 { get; set; }
        public string BladeOtherSerialNumber2 { get; set; }
        public bool BladeDamageIdentified { get; set; }
        public Nullable<long> BladeFaultCodeClassificationId { get; set; }
        public Nullable<long> BladeFaultCodeCauseId { get; set; }
        public Nullable<long> BladeFaultCodeTypeId { get; set; }
        public Nullable<long> BladeFaultCodeAreaId { get; set; }
        public Nullable<long> BladeClaimRelevantBooleanAnswerId { get; set; }
        public string BladeLsVtNumber { get; set; }
        public Nullable<System.DateTime> BladeLsCalibrationDate { get; set; }
        public Nullable<long> BladeLsLeewardSidePreRepairTip { get; set; }
        public Nullable<long> BladeLsLeewardSidePostRepairTip { get; set; }
        public Nullable<long> BladeLsLeewardSidePreRepair2 { get; set; }
        public Nullable<long> BladeLsLeewardSidePostRepair2 { get; set; }
        public Nullable<long> BladeLsLeewardSidePreRepair3 { get; set; }
        public Nullable<long> BladeLsLeewardSidePostRepair3 { get; set; }
        public Nullable<long> BladeLsLeewardSidePreRepair4 { get; set; }
        public Nullable<long> BladeLsLeewardSidePostRepair4 { get; set; }
        public Nullable<long> BladeLsLeewardSidePreRepair5 { get; set; }
        public Nullable<long> BladeLsLeewardSidePostRepair5 { get; set; }
        public Nullable<long> BladeLsWindwardSidePreRepairTip { get; set; }
        public Nullable<long> BladeLsWindwardSidePostRepairTip { get; set; }
        public Nullable<long> BladeLsWindwardSidePreRepair2 { get; set; }
        public Nullable<long> BladeLsWindwardSidePostRepair2 { get; set; }
        public Nullable<long> BladeLsWindwardSidePreRepair3 { get; set; }
        public Nullable<long> BladeLsWindwardSidePostRepair3 { get; set; }
        public Nullable<long> BladeLsWindwardSidePreRepair4 { get; set; }
        public Nullable<long> BladeLsWindwardSidePostRepair4 { get; set; }
        public Nullable<long> BladeLsWindwardSidePreRepair5 { get; set; }
        public Nullable<long> BladeLsWindwardSidePostRepair5 { get; set; }
        public string BladeInspectionReportDescription { get; set; }
        public Nullable<long> BladeManufacturerId { get; set; }
        public Nullable<long> BladeLsLeewardSidePreRepair6 { get; set; }
        public Nullable<long> BladeLsLeewardSidePostRepair6 { get; set; }
        public Nullable<long> BladeLsLeewardSidePreRepair7 { get; set; }
        public Nullable<long> BladeLsLeewardSidePostRepair7 { get; set; }
        public Nullable<long> BladeLsLeewardSidePreRepair8 { get; set; }
        public Nullable<long> BladeLsLeewardSidePostRepair8 { get; set; }
        public Nullable<long> BladeLsWindwardSidePreRepair6 { get; set; }
        public Nullable<long> BladeLsWindwardSidePostRepair6 { get; set; }
        public Nullable<long> BladeLsWindwardSidePreRepair7 { get; set; }
        public Nullable<long> BladeLsWindwardSidePostRepair7 { get; set; }
        public Nullable<long> BladeLsWindwardSidePreRepair8 { get; set; }
        public Nullable<long> BladeLsWindwardSidePostRepair8 { get; set; }
    
        public virtual BladeColor BladeColor { get; set; }
        public virtual BladeLength BladeLength { get; set; }
        public virtual ICollection<ComponentInspectionReportBladeDamage> ComponentInspectionReportBladeDamage { get; set; }
        public virtual ICollection<ComponentInspectionReportBladeRepairRecord> ComponentInspectionReportBladeRepairRecord { get; set; }
        public virtual ComponentInspectionReport ComponentInspectionReport { get; set; }
    }
}
