//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentInspectionReportGenerator
    {
        public long ComponentInspectionReportGeneratorId { get; set; }
        public long ComponentInspectionReportId { get; set; }
        public string VestasUniqueIdentifier { get; set; }
        public long GeneratorManufacturerId { get; set; }
        public string GeneratorSerialNumber { get; set; }
        public string OtherManufacturer { get; set; }
        public decimal GeneratorMaxTemperature { get; set; }
        public System.DateTime GeneratorMaxTemperatureResetDate { get; set; }
        public long CouplingId { get; set; }
        public long ActionToBeTakenOnGeneratorId { get; set; }
        public long GeneratorDriveEndId { get; set; }
        public long GeneratorNonDriveEndId { get; set; }
        public long GeneratorRotorId { get; set; }
        public long GeneratorCoverId { get; set; }
        public Nullable<long> AirToAirCoolerInternalId { get; set; }
        public Nullable<long> AirToAirCoolerExternalId { get; set; }
        public string GeneratorComments { get; set; }
        public Nullable<decimal> UGround { get; set; }
        public Nullable<decimal> VGround { get; set; }
        public Nullable<decimal> WGround { get; set; }
        public Nullable<decimal> UV { get; set; }
        public Nullable<decimal> UW { get; set; }
        public Nullable<decimal> VW { get; set; }
        public Nullable<decimal> KGround { get; set; }
        public Nullable<decimal> LGround { get; set; }
        public Nullable<decimal> MGround { get; set; }
        public Nullable<long> UGroundOhmUnitId { get; set; }
        public Nullable<long> VGroundOhmUnitId { get; set; }
        public Nullable<long> WGroundOhmUnitId { get; set; }
        public Nullable<long> UVOhmUnitId { get; set; }
        public Nullable<long> UWOhmUnitId { get; set; }
        public Nullable<long> VWOhmUnitId { get; set; }
        public Nullable<long> KGroundOhmUnitId { get; set; }
        public Nullable<long> LGroundOhmUnitId { get; set; }
        public Nullable<long> MGroundOhmUnitId { get; set; }
        public Nullable<long> U1U2 { get; set; }
        public Nullable<long> V1V2 { get; set; }
        public Nullable<long> W1W2 { get; set; }
        public Nullable<long> K1L1 { get; set; }
        public Nullable<long> L1M1 { get; set; }
        public Nullable<long> K1M1 { get; set; }
        public Nullable<long> K2L2 { get; set; }
        public Nullable<long> L2M2 { get; set; }
        public Nullable<long> K2M2 { get; set; }
        public bool GeneratorRewoundLocally { get; set; }
        public Nullable<long> GeneratorClaimRelevantBooleanAnswerId { get; set; }
        public bool InsulationComments { get; set; }
        public string GeneratorInsulationComments { get; set; }
    
        public virtual GeneratorManufacturer GeneratorManufacturer { get; set; }
        public virtual ComponentInspectionReport ComponentInspectionReport { get; set; }
    }
}
