//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentInspectionReportSkiiPFailedComponent
    {
        public long ComponentInspectionReportSkiiPFailedComponentId { get; set; }
        public long ComponentInspectionReportSkiiPId { get; set; }
        public string SkiiPFailedComponentVestasUniqueIdentifier { get; set; }
        public string SkiiPFailedComponentVestasItemNumber { get; set; }
        public string SkiiPFailedComponentSerialNumber { get; set; }
    
        public virtual ComponentInspectionReportSkiiP ComponentInspectionReportSkiiP { get; set; }
    }
}
