//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentInspectionReportSkiiP
    {
        public ComponentInspectionReportSkiiP()
        {
            this.ComponentInspectionReportSkiiPFailedComponent = new HashSet<ComponentInspectionReportSkiiPFailedComponent>();
            this.ComponentInspectionReportSkiiPNewComponent = new HashSet<ComponentInspectionReportSkiiPNewComponent>();
        }
    
        public long ComponentInspectionReportSkiiPId { get; set; }
        public long ComponentInspectionReportId { get; set; }
        public string SkiiPOtherDamagedComponentsReplaced { get; set; }
        public long SkiiPCauseId { get; set; }
        public long SkiiPQuantityOfFailedModules { get; set; }
        public Nullable<long> SkiiP2MWV521BooleanAnswerId { get; set; }
        public Nullable<long> SkiiP2MWV522BooleanAnswerId { get; set; }
        public Nullable<long> SkiiP2MWV523BooleanAnswerId { get; set; }
        public Nullable<long> SkiiP2MWV524BooleanAnswerId { get; set; }
        public Nullable<long> SkiiP2MWV525BooleanAnswerId { get; set; }
        public Nullable<long> SkiiP2MWV526BooleanAnswerId { get; set; }
        public Nullable<long> SkiiP3MWV521BooleanAnswerId { get; set; }
        public Nullable<long> SkiiP3MWV522BooleanAnswerId { get; set; }
        public Nullable<long> SkiiP3MWV523BooleanAnswerId { get; set; }
        public Nullable<long> SkiiP3MWV524xBooleanAnswerId { get; set; }
        public Nullable<long> SkiiP3MWV524yBooleanAnswerId { get; set; }
        public Nullable<long> SkiiP3MWV525xBooleanAnswerId { get; set; }
        public Nullable<long> SkiiP3MWV525yBooleanAnswerId { get; set; }
        public Nullable<long> SkiiP3MWV526xBooleanAnswerId { get; set; }
        public Nullable<long> SkiiP3MWV526yBooleanAnswerId { get; set; }
        public Nullable<long> SkiiP850KWV520BooleanAnswerId { get; set; }
        public Nullable<long> SkiiP850KWV524BooleanAnswerId { get; set; }
        public Nullable<long> SkiiP850KWV525BooleanAnswerId { get; set; }
        public Nullable<long> SkiiP850KWV526BooleanAnswerId { get; set; }
        public Nullable<long> SkiiPClaimRelevantBooleanAnswerId { get; set; }
        public Nullable<long> SkiiPNumberofComponents { get; set; }
    
        public virtual ICollection<ComponentInspectionReportSkiiPFailedComponent> ComponentInspectionReportSkiiPFailedComponent { get; set; }
        public virtual ICollection<ComponentInspectionReportSkiiPNewComponent> ComponentInspectionReportSkiiPNewComponent { get; set; }
        public virtual ComponentInspectionReport ComponentInspectionReport { get; set; }
    }
}
