//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicFieldsName
    {
        public DynamicFieldsName()
        {
            this.DynamicFieldsValue = new HashSet<DynamicFieldsValue>();
        }
    
        public int FieldId { get; set; }
        public string FieldName { get; set; }
        public Nullable<int> ControlId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public string TemplateVersion { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Description { get; set; }
    
        public virtual DynamicControlTypes DynamicControlTypes { get; set; }
        public virtual ICollection<DynamicFieldsValue> DynamicFieldsValue { get; set; }
    }
}
