//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicControlTypes
    {
        public DynamicControlTypes()
        {
            this.DynamicFieldsName = new HashSet<DynamicFieldsName>();
        }
    
        public int ControlId { get; set; }
        public string ControlType { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<DynamicFieldsName> DynamicFieldsName { get; set; }
    }
}
