//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicTableInput
    {
        public int Id { get; set; }
        public string CirId { get; set; }
        public string Row1Col1 { get; set; }
        public string Row1Col2 { get; set; }
        public string Row1Col3 { get; set; }
        public string Row1Col4 { get; set; }
        public string Row2Col1 { get; set; }
        public string Row2Col2 { get; set; }
        public string Row2Col3 { get; set; }
        public string Row2Col4 { get; set; }
        public string Row3Col1 { get; set; }
        public string Row3Col2 { get; set; }
        public string Row3Col3 { get; set; }
        public string Row3Col4 { get; set; }
        public string Row4Col1 { get; set; }
        public string Row4Col2 { get; set; }
        public string Row4Col3 { get; set; }
        public string Row4Col4 { get; set; }
        public string Row5Col1 { get; set; }
        public string Row5Col2 { get; set; }
        public string Row5Col3 { get; set; }
        public string Row5Col4 { get; set; }
        public string Row6Col1 { get; set; }
        public string Row6Col2 { get; set; }
        public string Row6Col3 { get; set; }
        public string Row6Col4 { get; set; }
        public string Row7Col1 { get; set; }
        public string Row7Col2 { get; set; }
        public string Row7Col3 { get; set; }
        public string Row7Col4 { get; set; }
        public string Row8Col1 { get; set; }
        public string Row8Col2 { get; set; }
        public string Row8Col3 { get; set; }
        public string Row8Col4 { get; set; }
        public string Row9Col1 { get; set; }
        public string Row9Col2 { get; set; }
        public string Row9Col3 { get; set; }
        public string Row9Col4 { get; set; }
        public string Row10Col1 { get; set; }
        public string Row10Col2 { get; set; }
        public string Row10Col3 { get; set; }
        public string Row10Col4 { get; set; }
        public string Row1Col5 { get; set; }
        public string Row1Col6 { get; set; }
        public string Row2Col5 { get; set; }
        public string Row2Col6 { get; set; }
        public string Row3Col5 { get; set; }
        public string Row3Col6 { get; set; }
        public string Row4Col5 { get; set; }
        public string Row4Col6 { get; set; }
        public string Row5Col5 { get; set; }
        public string Row5Col6 { get; set; }
        public string Row6Col5 { get; set; }
        public string Row6Col6 { get; set; }
        public string Row7Col5 { get; set; }
        public string Row7Col6 { get; set; }
        public string Row8Col5 { get; set; }
        public string Row8Col6 { get; set; }
        public string Row9Col5 { get; set; }
        public string Row9Col6 { get; set; }
        public string Row10Col5 { get; set; }
        public string Row10Col6 { get; set; }
        public string Row11Col1 { get; set; }
        public string Row11Col2 { get; set; }
        public string Row11Col3 { get; set; }
        public string Row11Col4 { get; set; }
        public string Row11Col5 { get; set; }
        public string Row11Col6 { get; set; }
        public string Row12Col1 { get; set; }
        public string Row12Col2 { get; set; }
        public string Row12Col3 { get; set; }
        public string Row12Col4 { get; set; }
        public string Row12Col5 { get; set; }
        public string Row12Col6 { get; set; }
        public string Row13Col1 { get; set; }
        public string Row13Col2 { get; set; }
        public string Row13Col3 { get; set; }
        public string Row13Col4 { get; set; }
        public string Row13Col5 { get; set; }
        public string Row13Col6 { get; set; }
        public string Row14Col1 { get; set; }
        public string Row14Col2 { get; set; }
        public string Row14Col3 { get; set; }
        public string Row14Col4 { get; set; }
        public string Row14Col5 { get; set; }
        public string Row14Col6 { get; set; }
    }
}
