//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditHistory
    {
        public long EditHistoryId { get; set; }
        public long ComponentInspectionReportId { get; set; }
        public string EditInitials { get; set; }
        public System.DateTime EditDate { get; set; }
        public long EditVersion { get; set; }
        public string EditReason { get; set; }
    }
}
