//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackType
    {
        public FeedbackType()
        {
            this.CirFeedback = new HashSet<CirFeedback>();
            this.CirFeedback1 = new HashSet<CirFeedback>();
        }
    
        public long FeedbackTypeId { get; set; }
        public string Name { get; set; }
        public int Sort { get; set; }
    
        public virtual ICollection<CirFeedback> CirFeedback { get; set; }
        public virtual ICollection<CirFeedback> CirFeedback1 { get; set; }
    }
}
