//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBXirData
    {
        public GBXirData()
        {
            this.GBXirWordDocument = new HashSet<GBXirWordDocument>();
        }
    
        public long GBXirDataID { get; set; }
        public string GBXirCode { get; set; }
        public int RevisionNumber { get; set; }
        public string OilAnalysis { get; set; }
        public string CMSAnalysis { get; set; }
        public string Analysis { get; set; }
        public string ConclusionsAndRecommendations { get; set; }
        public string CirIDs { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public string ModifiedBy { get; set; }
        public bool Deleted { get; set; }
        public string GearboxSerialNos { get; set; }
    
        public virtual ICollection<GBXirWordDocument> GBXirWordDocument { get; set; }
    }
}
