//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class GearboxManufacturer
    {
        public GearboxManufacturer()
        {
            this.ComponentInspectionReportGeneral = new HashSet<ComponentInspectionReportGeneral>();
            this.GearboxManufacturer1 = new HashSet<GearboxManufacturer>();
            this.ComponentInspectionReportGearbox = new HashSet<ComponentInspectionReportGearbox>();
        }
    
        public long GearboxManufacturerId { get; set; }
        public string Name { get; set; }
        public long LanguageId { get; set; }
        public Nullable<long> ParentGearboxManufacturerId { get; set; }
        public long Sort { get; set; }
        public string Email { get; set; }
        public string Cc { get; set; }
        public string EmailContactName { get; set; }
        public string Brand { get; set; }
    
        public virtual ICollection<ComponentInspectionReportGeneral> ComponentInspectionReportGeneral { get; set; }
        public virtual ICollection<GearboxManufacturer> GearboxManufacturer1 { get; set; }
        public virtual GearboxManufacturer GearboxManufacturer2 { get; set; }
        public virtual ICollection<ComponentInspectionReportGearbox> ComponentInspectionReportGearbox { get; set; }
    }
}
