//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneratorManufacturer
    {
        public GeneratorManufacturer()
        {
            this.ComponentInspectionReportGeneral = new HashSet<ComponentInspectionReportGeneral>();
            this.GeneratorManufacturer1 = new HashSet<GeneratorManufacturer>();
            this.ComponentInspectionReportGearbox = new HashSet<ComponentInspectionReportGearbox>();
            this.ComponentInspectionReportGearbox1 = new HashSet<ComponentInspectionReportGearbox>();
            this.ComponentInspectionReportGenerator = new HashSet<ComponentInspectionReportGenerator>();
        }
    
        public long GeneratorManufacturerId { get; set; }
        public string Name { get; set; }
        public long LanguageId { get; set; }
        public Nullable<long> ParentGeneratorManufacturerId { get; set; }
        public long Sort { get; set; }
        public string Email { get; set; }
        public string Cc { get; set; }
        public string EmailContactName { get; set; }
        public string Brand { get; set; }
    
        public virtual ICollection<ComponentInspectionReportGeneral> ComponentInspectionReportGeneral { get; set; }
        public virtual ICollection<GeneratorManufacturer> GeneratorManufacturer1 { get; set; }
        public virtual GeneratorManufacturer GeneratorManufacturer2 { get; set; }
        public virtual ICollection<ComponentInspectionReportGearbox> ComponentInspectionReportGearbox { get; set; }
        public virtual ICollection<ComponentInspectionReportGearbox> ComponentInspectionReportGearbox1 { get; set; }
        public virtual ICollection<ComponentInspectionReportGenerator> ComponentInspectionReportGenerator { get; set; }
    }
}
