//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class GirData
    {
        public GirData()
        {
            this.GirWordDocument = new HashSet<GirWordDocument>();
        }
    
        public long GirDataID { get; set; }
        public string GirCode { get; set; }
        public int RevisionNumber { get; set; }
        public string ConclusionsAndRecommendations { get; set; }
        public string CirIDs { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public string ModifiedBy { get; set; }
        public bool Deleted { get; set; }
        public string GeneralSerialNos { get; set; }
        public string ClassificationOfDamage { get; set; }
        public string AnalysisOfPicture { get; set; }
        public string AnalysisOfMeasurments { get; set; }
    
        public virtual ICollection<GirWordDocument> GirWordDocument { get; set; }
    }
}
