//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageDataInfo
    {
        public int ImageDataInfoId { get; set; }
        public long ComponentInspectionReportId { get; set; }
        public Nullable<bool> IsPlateTypeNotPossible { get; set; }
        public string PlateTypeNotPossibleReason { get; set; }
    
        public virtual ComponentInspectionReport ComponentInspectionReport { get; set; }
    }
}
