//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageData
    {
        public int ImageId { get; set; }
        public long ComponentInspectionReportId { get; set; }
        public string ImageDataString { get; set; }
        public string ImageDescription { get; set; }
        public Nullable<int> ImageOrder { get; set; }
        public string InspectionDesc { get; set; }
        public Nullable<bool> IsPlateType { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> FlangNo { get; set; }
        public string SketchURL { get; set; }
        public string FormIOImageGUID { get; set; }
    
        public virtual ComponentInspectionReport ComponentInspectionReport { get; set; }
    }
}
