//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainBearingManufacturer
    {
        public MainBearingManufacturer()
        {
            this.ComponentInspectionReportMainBearing = new HashSet<ComponentInspectionReportMainBearing>();
            this.ComponentInspectionReportMainBearing1 = new HashSet<ComponentInspectionReportMainBearing>();
            this.MainBearingManufacturer1 = new HashSet<MainBearingManufacturer>();
        }
    
        public long MainBearingManufacturerId { get; set; }
        public string Name { get; set; }
        public long LanguageId { get; set; }
        public Nullable<long> ParentMainBearingManufacturerId { get; set; }
        public long Sort { get; set; }
        public string Brand { get; set; }
    
        public virtual ICollection<ComponentInspectionReportMainBearing> ComponentInspectionReportMainBearing { get; set; }
        public virtual ICollection<ComponentInspectionReportMainBearing> ComponentInspectionReportMainBearing1 { get; set; }
        public virtual ICollection<MainBearingManufacturer> MainBearingManufacturer1 { get; set; }
        public virtual MainBearingManufacturer MainBearingManufacturer2 { get; set; }
    }
}
