//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDF
    {
        public long PDFId { get; set; }
        public byte[] PDFData { get; set; }
        public int CIRState { get; set; }
        public string CIRTemplateGUID { get; set; }
        public string CIRName { get; set; }
    }
}
