//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptNotification
    {
        public long ReceiptNotificationId { get; set; }
        public long ComponentInspectionReportId { get; set; }
        public string InfoPathFilename { get; set; }
        public Nullable<System.DateTime> SendOn { get; set; }
        public string SendTo { get; set; }
        public Nullable<decimal> CirVersion { get; set; }
    }
}
