//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportType
    {
        public ReportType()
        {
            this.ReportType1 = new HashSet<ReportType>();
            this.ComponentInspectionReport = new HashSet<ComponentInspectionReport>();
        }
    
        public long ReportTypeId { get; set; }
        public string Name { get; set; }
        public long LanguageId { get; set; }
        public Nullable<long> ParentReportTypeId { get; set; }
        public long Sort { get; set; }
    
        public virtual ICollection<ReportType> ReportType1 { get; set; }
        public virtual ReportType ReportType2 { get; set; }
        public virtual ICollection<ComponentInspectionReport> ComponentInspectionReport { get; set; }
    }
}
