//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBU
    {
        public SBU()
        {
            this.RejectNotification = new HashSet<RejectNotification>();
            this.SBUNotification = new HashSet<SBUNotification>();
            this.SBURejectNotification = new HashSet<SBURejectNotification>();
            this.SecondNotification = new HashSet<SecondNotification>();
            this.FirstNotification = new HashSet<FirstNotification>();
            this.ComponentInspectionReport = new HashSet<ComponentInspectionReport>();
        }
    
        public long SBUId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public long VPDptId { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<RejectNotification> RejectNotification { get; set; }
        public virtual ICollection<SBUNotification> SBUNotification { get; set; }
        public virtual ICollection<SBURejectNotification> SBURejectNotification { get; set; }
        public virtual ICollection<SecondNotification> SecondNotification { get; set; }
        public virtual ICollection<FirstNotification> FirstNotification { get; set; }
        public virtual ICollection<ComponentInspectionReport> ComponentInspectionReport { get; set; }
    }
}
