//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBUNotification
    {
        public long SBUNotificationId { get; set; }
        public long ComponentInspectionReportId { get; set; }
        public Nullable<System.DateTime> SendOn { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string State { get; set; }
        public string ComponentType { get; set; }
        public Nullable<long> TurbineMatrixId { get; set; }
        public string Sitename { get; set; }
        public Nullable<long> CountryISOId { get; set; }
        public long SBUId { get; set; }
        public Nullable<long> CIMCaseNo { get; set; }
        public short Warning { get; set; }
    
        public virtual SBU SBU { get; set; }
        public virtual CountryISO CountryISO { get; set; }
    }
}
