//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBURejectNotification
    {
        public long SBURejectNotificationId { get; set; }
        public long ComponentInspectionReportId { get; set; }
        public string InfoPathFilename { get; set; }
        public Nullable<System.DateTime> SendOn { get; set; }
        public string RejectedBy { get; set; }
        public string Comment { get; set; }
        public Nullable<long> SBUId { get; set; }
        public Nullable<long> CIMCaseNo { get; set; }
    
        public virtual SBU SBU { get; set; }
    }
}
