//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecondNotification
    {
        public long SecondNotificationId { get; set; }
        public long ComponentInspectionReportId { get; set; }
        public Nullable<System.DateTime> SendOn { get; set; }
        public Nullable<long> ManufacturerID { get; set; }
        public long SBUId { get; set; }
        public string ComponentType { get; set; }
        public byte[] CIRTemplate { get; set; }
        public long CIMCaseNumber { get; set; }
        public Nullable<long> TurbineMatrixId { get; set; }
        public Nullable<long> CirDataId { get; set; }
    
        public virtual CirData CirData { get; set; }
        public virtual SBU SBU { get; set; }
    }
}
