//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceReportNumberType
    {
        public ServiceReportNumberType()
        {
            this.ServiceReportNumberType1 = new HashSet<ServiceReportNumberType>();
            this.ComponentInspectionReport = new HashSet<ComponentInspectionReport>();
        }
    
        public long ServiceReportNumberTypeId { get; set; }
        public string Name { get; set; }
        public long LanguageId { get; set; }
        public Nullable<long> ParentServiceReportNumberTypeId { get; set; }
        public long Sort { get; set; }
    
        public virtual ICollection<ServiceReportNumberType> ServiceReportNumberType1 { get; set; }
        public virtual ServiceReportNumberType ServiceReportNumberType2 { get; set; }
        public virtual ICollection<ComponentInspectionReport> ComponentInspectionReport { get; set; }
    }
}
