//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateDynamicTableDef
    {
        public int Id { get; set; }
        public string CIMcaseNo { get; set; }
        public string TableHeader { get; set; }
        public string ColHeader1 { get; set; }
        public string ColHeader2 { get; set; }
        public string ColHeader3 { get; set; }
        public string ColHeader4 { get; set; }
        public string RowHeader1 { get; set; }
        public string RowHeader2 { get; set; }
        public string RowHeader3 { get; set; }
        public string RowHeader4 { get; set; }
        public string RowHeader5 { get; set; }
        public string RowHeader6 { get; set; }
        public string RowHeader7 { get; set; }
        public string RowHeader8 { get; set; }
        public string RowHeader9 { get; set; }
        public string RowHeader10 { get; set; }
        public string ColHeader5 { get; set; }
        public string ColHeader6 { get; set; }
        public string RowHeader11 { get; set; }
        public string RowHeader12 { get; set; }
        public string RowHeader13 { get; set; }
        public string RowHeader14 { get; set; }
    }
}
