//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurbineData
    {
        public int TurbineDataId { get; set; }
        public string TurbineId { get; set; }
        public string TurbineType { get; set; }
        public string Voltage { get; set; }
        public string Frequency { get; set; }
        public string RotorDiameter { get; set; }
        public string NominalPower { get; set; }
        public string PowerRegulation { get; set; }
        public string SmallGenerator { get; set; }
        public string TemperatureVariant { get; set; }
        public string MkVersion { get; set; }
        public string OnshoreOffshore { get; set; }
        public string Manufacturer { get; set; }
        public string Country { get; set; }
        public string Site { get; set; }
        public string LocalTurbineId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
    }
}
