//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurbineMatrix
    {
        public long TurbineMatrixId { get; set; }
        public Nullable<long> TurbineId { get; set; }
        public Nullable<long> TurbinePowerRegulationId { get; set; }
        public Nullable<long> TurbineRotorDiameterId { get; set; }
        public Nullable<long> TurbineNominelPowerId { get; set; }
        public Nullable<long> TurbineVoltageId { get; set; }
        public Nullable<long> TurbineFrequencyId { get; set; }
        public Nullable<long> TurbineSmallGeneratorId { get; set; }
        public Nullable<long> TurbineTemperatureVariantId { get; set; }
        public Nullable<long> TurbineMarkVersionId { get; set; }
        public Nullable<long> TurbinePlacementId { get; set; }
        public Nullable<long> TurbineManufacturerId { get; set; }
        public Nullable<long> TurbineOldId { get; set; }
        public string Comment { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
    
        public virtual TurbineManufacturer TurbineManufacturer { get; set; }
        public virtual Turbine Turbine { get; set; }
    }
}
