//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cir.Sync.Services.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurbineManufacturer
    {
        public TurbineManufacturer()
        {
            this.TurbineMatrix = new HashSet<TurbineMatrix>();
        }
    
        public long TurbineManufacturerId { get; set; }
        public string Manufacturer { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
    
        public virtual ICollection<TurbineMatrix> TurbineMatrix { get; set; }
    }
}
